export interface BotRow { id: number; name: string; symbol: string; timeframe: string; intervalSec: number; strategy: string; params: Record<string, number>; risk: Record<string, number>; mode: string; status: string; allocationUsd: number; pairId: string | null; createdAt: number; lastRunAt: number | null; lastSignal: Record<string, unknown> | null; lastError: string | null; haltedUntil: number | null }
export interface PositionRow { id: number; botId: number | null; symbol: string; side: string; qty: number; entryPrice: number; entryAt: number; stopLoss: number | null; takeProfit: number | null; trailingStopPct: number | null; highWater: number | null; status: string; exitPrice: number | null; exitAt: number | null; exitReason: string | null; pnl: number | null; pnlPct: number | null; mode: string; source: string; pairId: string | null; entryLiquidity: number | null }
export interface TradeRow { id: number; botId: number | null; positionId: number | null; symbol: string; side: string; qty: number; price: number; fee: number; mode: string; reason: string | null; exchangeOrderId: string | null; createdAt: number; pairId: string | null }
export interface SuggestionRow { id: number; scanId: number | null; symbol: string; side: string; entry: number; stopLoss: number; takeProfit: number; confidence: number; timeframe: string; rationale: string; riskReward: number | null; status: string; createdAt: number; pairId: string | null }
export interface ScanRow { id: number; createdAt: number; summary: string; regime: string | null; universe: string[]; model: string | null; inputTokens: number | null; outputTokens: number | null }
export interface LogRow { id: number; ts: number; level: string; botId: number | null; message: string }
export interface EquityRow { id: number; ts: number; mode: string; equity: number; cash: number }
export interface EngineStateRow { id: number; startedAt: number | null; heartbeat: number | null; pid: number | null; ticks: number }
export interface DexTickRow { pairId: string; ts: number; price: number; liq: number | null }
